[build]
  base = "frontend"
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: set env var here when using netlify-cli. In dashboard, set VITE_API_BASE to your backend URL.